name: Build

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libtirpc-dev
      - name: Bootstrap
        run: ./bootstrap
      - name: Configure
        run: |
          mkdir build
          cd build
          ../configure --prefix=/usr
      - name: Build
        working-directory: build
        run: make
      - name: Install
        working-directory: build
        run: |
          NAME=unfs3-`arch`-g`git rev-parse --short HEAD`
          mkdir $NAME
          make install DESTDIR=`pwd`/$NAME
          tar -acf $NAME.tar.xz $NAME
      - uses: actions/upload-artifact@v3
        with:
          name: Linux (Ubuntu)
          path: build/unfs3-*.tar.xz

  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
      - name: Install dependencies
        run: |
          pacman --sync --noconfirm --needed \
            make gcc autotools flex git
          pacman --sync --noconfirm --needed \
            libtirpc-devel
      - name: Bootstrap
        run: ./bootstrap
      - name: Configure
        run: |
          mkdir build
          cd build
          ../configure --prefix=/usr
      - name: DEBUG
        run: echo | gcc -dM -E -
      - name: DEBUG
        run: echo '#include <winsock2.h>' | gcc -E -
      - name: Build
        working-directory: build
        run: make
      - name: Install
        working-directory: build
        run: |
          NAME=unfs3-`arch`-g`git rev-parse --short HEAD`
          mkdir $NAME
          make install DESTDIR=`pwd`/$NAME
          tar -acf $NAME.tar.xz $NAME
      - uses: actions/upload-artifact@v3
        with:
          name: Windows
          path: build/unfs3-*.tar.xz
